#!/bin/bash

if [ ! -e $target/root/.ssh ]; then
	mkdir -p $target/root/.ssh
fi
chmod 644 $target/root/.ssh/authorized_keys
ainsl -asvD /root/.ssh/authorized_keys 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGHGpdMfBUUfy2+nXYN9OegduQ9thqGh28bX5LtpFBck thomas@lordotter.de'
